version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 15...
      - curl -fsSL https://rpm.nodesource.com/setup_current.x | bash -
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Testing...
      - npm test
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
